apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: shreyanshgohil2510/backend
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: REACT_APP_BASE_URL
              value: "https://satva-react.com"
            - name: ACCESS_TOKEN_SECRET_KEY
              value: "cbdf5ac1-5c6a-409e-9d03-b13e53b594c0"
            - name: REFRESH_TOKEN_SECRET_KEY
              value: "7285bbf9-8c86-4ea8-874e-8fdb29adaa2f"
            - name: FORGOT_PASSWORD_TOKEN_SECRET_KEY
              value: "694e7d56-496f-4fff-8f5e-f166df6bedc2"
            - name: SESSION_SECRET_KEY
              value: "4dc11da1-d5b6-4b02-98ae-5d612169fa9b"
            - name: SMTP_EMAIL
              value: "dev@satva.solutions"
            - name: SMTP_EMAIL_LOGIN
              value: "AKIA2Q6P5ZQZJM5CKTOS"
            - name: SMTP_PASSWORD
              value: "BA0ac4HW8pysr27wMU4vR3LYe+vm2WhJUs8/KJhn44Ew"
            - name: SMTP_HOST
              value: "email-smtp.us-west-2.amazonaws.com"
            - name: SMTP_PORT
              value: '587'
            - name: S3_ACCESSKEYID
              value: "AKIARU7YIFI57PKK5TPL"
            - name: S3_SECRETACCESSKEY
              value: "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"
            - name: QUICKBOOKS_CLIENT_ID
              value: "ABkgXq13iCd8U1UkAyxCDnpNSyVkelzggZphvggbUBss99WaoJ"
            - name: QUICKBOOKS_CLIENT_SECRET
              value: "jh1L2aH4MPC5myY6LCZkNyUHMwmdwjpEnvpGPsSw"
            - name: QUICKBOOKS_ENVIRONMENT
              value: "sandbox"
            - name: QUICKBOOKS_REDIRECT_URI
              value: "https://satva-react.com/callback"
            - name: QUICKBOOKS_SCOPES
              value: "com.intuit.quickbooks.accounting,openid,email,profile"
            - name: QUICKBOOKS_TOKEN_REVOKE_ENDPOINT
              value: "https://developer.api.intuit.com/v2/oauth2/tokens/revoke"
            - name: QUICKBOOKS_USER_INFO_ENDPOINT
              value: "https://sandbox-accounts.platform.intuit.com/v1/openid_connect/userinfo"
            - name: PG_USER
              value: postgres
            - name: PG_HOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: cost-allocation-pro
            - name: DATABASE_URL
              value: postgresql://postgres:12345@postgres-cluster-ip-service:5432/cost-allocation-pro?schema=public
            - name: PGPASSWORD
              value: postgres